
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blogger_app_webops_production

  redis:
    image: redis:7


  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/Blogger_app_webops
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      DATABASE_NAME: blogger_app_webops_production
      REDIS_URL: redis://redis:6379/1

